vals = [{"uId":"3","Name":"ช้วน","Father":"บุญ","Mom":"-","Sex":"F","Status":"0"},
{"uId":"4","Name":"พิม","Father":"บุญ","Mom":"-","Sex":"F","Status":"0"},
{"uId":"5","Name":"พวน","Father":"บุญ","Mom":"-","Sex":"F","Status":"0"},
{"uId":"6","Name":"อาจ","Father":"บุญ","Mom":"-","Sex":"M","Status":"0"},
{"uId":"7","Name":"เอียด","Father":"บุญ","Mom":"-","Sex":"F","Status":"0"},
{"uId":"8","Name":"ออ","Father":"บุญ","Mom":"-","Sex":"F","Status":"0"},
{"uId":"9","Name":"ออง","Father":"บุญ","Mom":"-","Sex":"F","Status":"0"},
{"uId":"10","Name":"ควญ","Father":"บุญ","Mom":"-","Sex":"F","Status":"0"},
{"uId":"11","Name":"เครือ","Father":"บุญ","Mom":"-","Sex":"F","Status":"0"},
{"uId":"12","Name":"เยี่ยม","Father":"บุญ","Mom":"-","Sex":"M","Status":"0"},
{"uId":"13","Name":"ยั่ว","Father":"บุญ","Mom":"-","Sex":"M","Status":"0"},
{"uId":"14","Name":"วิเชียร","Father":"-","Mom":"ช้วน","Sex":"F","Status":"0"},
{"uId":"15","Name":"อุบล","Father":"-","Mom":"ช้วน","Sex":"F","Status":"1"},
{"uId":"16","Name":"นัน","Father":"-","Mom":"พิม","Sex":"F","Status":"0"},
{"uId":"17","Name":"นะ","Father":"-","Mom":"พิม","Sex":"M","Status":"0"},
{"uId":"18","Name":"สมศักดิ์","Father":"-","Mom":"พวน","Sex":"M","Status":"0"},
{"uId":"19","Name":"พะเยา","Father":"-","Mom":"พวน","Sex":"F","Status":"1"},
{"uId":"20","Name":"กันยา","Father":"-","Mom":"พวน","Sex":"F","Status":"1"},
{"uId":"21","Name":"ไพศาล","Father":"-","Mom":"พวน","Sex":"M","Status":"0"},
{"uId":"22","Name":"กอบแก้ว","Father":"-","Mom":"พวน","Sex":"F","Status":"1"},
{"uId":"23","Name":"อุไทยวรรณ","Father":"-","Mom":"พวน","Sex":"F","Status":"1"},
{"uId":"24","Name":"กาญจนา","Father":"-","Mom":"พวน","Sex":"F","Status":"1"},
{"uId":"25","Name":"เทือง","Father":"อาจ","Mom":"- ","Sex":"F","Status":"0"},
{"uId":"26","Name":"เอิญ","Father":"-","Mom":"เอียด","Sex":"F","Status":"0"},
{"uId":"27","Name":"กิ้น","Father":"-","Mom":"เอียด","Sex":"F","Status":"0"},
{"uId":"28","Name":"แจ๊ว","Father":"-","Mom":"เอียด","Sex":"F","Status":"1"},
{"uId":"29","Name":"ตู๋","Father":"-","Mom":"เอียด","Sex":"M","Status":"1"},
{"uId":"30","Name":"คเน","Father":"-","Mom":"ออ","Sex":"M","Status":"1"},
{"uId":"31","Name":"ชำนาญ","Father":"-","Mom":"ออ","Sex":"M","Status":"0"},
{"uId":"32","Name":"คำนวน","Father":"-","Mom":"ออ","Sex":"F","Status":"1"},
{"uId":"33","Name":"ธนู","Father":"-","Mom":"ออง","Sex":"M","Status":"1"},
{"uId":"34","Name":"วินัย","Father":"-","Mom":"ออง","Sex":"M","Status":"0"},
{"uId":"35","Name":"ธานี","Father":"-","Mom":"ออง","Sex":"M","Status":"0"},
{"uId":"36","Name":"เบ็ญจา","Father":"-","Mom":"เครือ","Sex":"F","Status":"1"},
{"uId":"37","Name":"คมคาย","Father":"-","Mom":"เครือ","Sex":"F","Status":"1"},
{"uId":"38","Name":"โดม","Father":"เยี่ยม","Mom":"- ","Sex":"M","Status":"0"},
{"uId":"39","Name":"แดง","Father":"เยี่ยม","Mom":"- ","Sex":"F","Status":"1"},
{"uId":"40","Name":"แอ๊ด","Father":"เยี่ยม","Mom":"- ","Sex":"M","Status":"0"},
{"uId":"41","Name":"ป๊อก","Father":"เยี่ยม","Mom":"- ","Sex":"M","Status":"1"},
{"uId":"42","Name":"จุ๋มจิ๋ม","Father":"เยี่ยม","Mom":"- ","Sex":"F","Status":"1"},
{"uId":"43","Name":"นิตยา","Father":"ยั่ว","Mom":"- ","Sex":"F","Status":"1"},
{"uId":"44","Name":"อารี","Father":"ยั่ว","Mom":"- ","Sex":"F","Status":"1"},
{"uId":"45","Name":"ไก่","Father":"-","Mom":"วิเชียร","Sex":"F","Status":"0"},
{"uId":"46","Name":"กบ","Father":"-","Mom":"วิเชียร","Sex":"F","Status":"1"},
{"uId":"47","Name":"สุพัตรา","Father":"-","Mom":"วิเชียร","Sex":"F","Status":"1"},
{"uId":"48","Name":"ตู้น","Father":"-","Mom":"อุบล","Sex":"M","Status":"1"},
{"uId":"49","Name":"ต่อ","Father":"-","Mom":"อุบล","Sex":"M","Status":"1"},
{"uId":"50","Name":"ต่าย","Father":"-","Mom":"อุบล","Sex":"M","Status":"1"},
{"uId":"51","Name":"เป็ด","Father":"-","Mom":"นัน","Sex":"F","Status":"1"},
{"uId":"52","Name":"เบื๊อกใหญ่","Father":"-","Mom":"นัน","Sex":"M","Status":"1"},
{"uId":"53","Name":"เบื๊อกเล็ก","Father":"-","Mom":"นัน","Sex":"M","Status":"1"},
{"uId":"54","Name":"แหม่ว","Father":"-","Mom":"นัน","Sex":"F","Status":"1"},
{"uId":"55","Name":"โต้ง","Father":"-","Mom":"นะ","Sex":"M","Status":"1"},
{"uId":"56","Name":"ตั้ว","Father":"-","Mom":"นะ","Sex":"M","Status":"1"},
{"uId":"57","Name":"ต้อย","Father":"-","Mom":"นะ","Sex":"M","Status":"1"},
{"uId":"58","Name":"หญิง","Father":"-","Mom":"นะ","Sex":"F","Status":"1"},
{"uId":"59","Name":"ปุ๋ย","Father":"สมศักดิ์","Mom":"-","Sex":"F","Status":"1"},
{"uId":"60","Name":"อ้อ","Father":"สมศักดิ์","Mom":"-","Sex":"F","Status":"1"},
{"uId":"61","Name":"ทิพ","Father":"-","Mom":"พะเยา","Sex":"F","Status":"1"},
{"uId":"62","Name":"เม้า","Father":"-","Mom":"พะเยา","Sex":"F","Status":"1"},
{"uId":"63","Name":"เพรช","Father":"-","Mom":"พะเยา","Sex":"F","Status":"1"},
{"uId":"64","Name":"ดำ","Father":"-","Mom":"พะเยา","Sex":"F","Status":"1"},
{"uId":"65","Name":"หนึ่ง","Father":"-","Mom":"กันยา","Sex":"M","Status":"1"},
{"uId":"66","Name":"หนิง","Father":"-","Mom":"กันยา","Sex":"F","Status":"1"},
{"uId":"67","Name":"หญก","Father":"ไพศาล","Mom":"-","Sex":"F","Status":"1"},
{"uId":"68","Name":"กรีน","Father":"ไพศาล","Mom":"-","Sex":"F","Status":"1"},
{"uId":"69","Name":"เทป","Father":"-","Mom":"กอบแก้ว","Sex":"M","Status":"1"},
{"uId":"70","Name":"ทอป","Father":"-","Mom":"กอบแก้ว","Sex":"M","Status":"1"},
{"uId":"71","Name":"ทีม","Father":"-","Mom":"อุไทยวรรณ","Sex":"M","Status":"1"},
{"uId":"72","Name":"ยุ้ย","Father":"-","Mom":"อุไทยวรรณ","Sex":"F","Status":"1"},
{"uId":"73","Name":"น้ำ","Father":"-","Mom":"กาญจนา","Sex":"F","Status":"1"},
{"uId":"74","Name":"ภูมิ","Father":"-","Mom":"กาญจนา","Sex":"M","Status":"1"},
{"uId":"75","Name":"โหน่ง","Father":"-","Mom":"เทือง","Sex":"F","Status":"1"},
{"uId":"76","Name":"ศุกพชัย","Father":"-","Mom":"เทือง","Sex":"M","Status":"1"},
{"uId":"77","Name":"วรรณ","Father":"-","Mom":"เทือง","Sex":"F","Status":"1"},
{"uId":"78","Name":"มุกดา","Father":"-","Mom":"เทือง","Sex":"F","Status":"1"},
{"uId":"79","Name":"อุไร","Father":"-","Mom":"เทือง","Sex":"F","Status":"1"},
{"uId":"80","Name":"กุ้ง","Father":"-","Mom":"เอิญ","Sex":"M","Status":"0"},
{"uId":"81","Name":"น้อย","Father":"-","Mom":"เอิญ","Sex":"F","Status":"1"},
{"uId":"82","Name":"สัน","Father":"-","Mom":"เอิญ","Sex":"M","Status":"1"},
{"uId":"83","Name":"แม๋ง","Father":"-","Mom":"เอิญ","Sex":"F","Status":"1"},
{"uId":"84","Name":"น้ำเพรช","Father":"-","Mom":"เอิญ","Sex":"F","Status":"1"},
{"uId":"85","Name":"ฮุก","Father":"-","Mom":"เอิญ","Sex":"M","Status":"1"},
{"uId":"86","Name":"จ๊ะ","Father":"-","Mom":"แจ๊ว","Sex":"F","Status":"1"},
{"uId":"87","Name":"มา","Father":"-","Mom":"แจ๊ว","Sex":"F","Status":"1"},
{"uId":"88","Name":"ต้า","Father":"-","Mom":"แจ๊ว","Sex":"F","Status":"1"},
{"uId":"89","Name":"จ๋า","Father":"ตู๋","Mom":"-","Sex":"F","Status":"1"},
{"uId":"90","Name":"วิ","Father":"ชำนาญ","Mom":"-","Sex":"F","Status":"1"},
{"uId":"91","Name":"เชล์","Father":"ชำนาญ","Mom":"-","Sex":"F","Status":"1"},
{"uId":"92","Name":"แก๊ป","Father":"ชำนาญ","Mom":"-","Sex":"F","Status":"1"},
{"uId":"93","Name":"อิฐ","Father":"-","Mom":"คำนวน","Sex":"M","Status":"1"},
{"uId":"94","Name":"เอ็ก","Father":"-","Mom":"คำนวน","Sex":"M","Status":"1"},
{"uId":"95","Name":"เอี่ยว","Father":"-","Mom":"คำนวน","Sex":"M","Status":"1"},
{"uId":"96","Name":"ป่าน","Father":"ธนู","Mom":"-","Sex":"F","Status":"1"},
{"uId":"97","Name":"ปอ","Father":"ธนู","Mom":"-","Sex":"M","Status":"1"},
{"uId":"98","Name":"นุ่น","Father":"-","Mom":"ธานี","Sex":"F","Status":"1"},
{"uId":"99","Name":"น๊อต","Father":"-","Mom":"ธานี","Sex":"M","Status":"1"},
{"uId":"100","Name":"โอ๊ด","Father":"-","Mom":"เบ็ญจา","Sex":"F","Status":"1"},
{"uId":"101","Name":"น้ำ","Father":"-","Mom":"เบ็ญจา","Sex":"F","Status":"1"},
{"uId":"102","Name":"เป็นปลื้ม","Father":"-","Mom":"คมคาย","Sex":"M","Status":"1"},
{"uId":"103","Name":"ส้ม","Father":"โดม","Mom":"-","Sex":"F","Status":"1"},
{"uId":"104","Name":"ควีน","Father":"แดง","Mom":"-","Sex":"F","Status":"1"},
{"uId":"105","Name":"เดียว","Father":"แดง","Mom":"-","Sex":"M","Status":"1"},
{"uId":"106","Name":"ดิว","Father":"แดง","Mom":"-","Sex":"M","Status":"1"},
{"uId":"107","Name":"ปอ","Father":"แอ๊ด","Mom":"-","Sex":"M","Status":"1"},
{"uId":"108","Name":"ตานอย","Father":"แอ๊ด","Mom":"-","Sex":"M","Status":"1"},
{"uId":"109","Name":"ตุน","Father":"ป๊อก","Mom":"-","Sex":"M","Status":"1"},
{"uId":"110","Name":"ปอปอาย","Father":"ป๊อก","Mom":"-","Sex":"M","Status":"1"},
{"uId":"111","Name":"ติป","Father":"ป๊อก","Mom":"-","Sex":"M","Status":"1"},
{"uId":"112","Name":"เก๋ง","Father":"- ","Mom":"นิตยา","Sex":"F","Status":"1"},
{"uId":"113","Name":"จิป","Father":"- ","Mom":"นิตยา","Sex":"M","Status":"1"},
{"uId":"114","Name":"โป้ง","Father":"- ","Mom":"อารี","Sex":"M","Status":"1"},
{"uId":"115","Name":"โปรด","Father":"- ","Mom":"อารี","Sex":"M","Status":"1"},
{"uId":"116","Name":"บอส","Father":"-","Mom":"กบ","Sex":"-","Status":"1"},
{"uId":"117","Name":"ใบบัว","Father":"ต่อ","Mom":"-","Sex":"-","Status":"1"},
{"uId":"118","Name":"ตาว","Father":"-","Mom":"เป็ด","Sex":"F","Status":"1"},
{"uId":"119","Name":"ติป","Father":"-","Mom":"เป็ด","Sex":"F","Status":"1"},
{"uId":"120","Name":"เต๋","Father":"-","Mom":"เป็ด","Sex":"M","Status":"1"},
{"uId":"121","Name":"ใบบัว","Father":"เบื๊อกเล็ก","Mom":"-","Sex":"F","Status":"1"},
{"uId":"122","Name":"ใบหอม","Father":"เบื๊อกเล็ก","Mom":"-","Sex":"F","Status":"1"},
{"uId":"123","Name":"กัสจัง","Father":"-","Mom":"แหม่ว","Sex":"-","Status":"1"},
{"uId":"124","Name":"เกม","Father":"-","Mom":"แหม่ว","Sex":"-","Status":"1"},
{"uId":"125","Name":"ไตเติล","Father":"ตั้ว","Mom":"-","Sex":"-","Status":"1"},
{"uId":"126","Name":" แชมป์","Father":"-","Mom":"เม้า","Sex":"-","Status":"1"},
{"uId":"127","Name":"มิ้ง","Father":"-","Mom":"เม้า","Sex":"-","Status":"1"},
{"uId":"128","Name":"นิว","Father":"หนึ่ง","Mom":"-","Sex":"M","Status":"1"},
{"uId":"129","Name":"นน","Father":"-","Mom":"หนิง","Sex":"-","Status":"1"},
{"uId":"130","Name":"ราแม","Father":"-","Mom":"หญก","Sex":"F","Status":"1"},
{"uId":"131","Name":"ต้นกล้า","Father":"-","Mom":"กรีน","Sex":"M","Status":"1"},
{"uId":"132","Name":"กัปตัน","Father":"-","Mom":"กรีน","Sex":"M","Status":"1"},
{"uId":"133","Name":"ปืน","Father":"-","Mom":"น้อย","Sex":"-","Status":"1"},
{"uId":"134","Name":"ปลาย","Father":"-","Mom":"น้อย","Sex":"-","Status":"1"},
{"uId":"135","Name":"ของขวัญ","Father":"-","Mom":"มา","Sex":"F","Status":"1"},
{"uId":"136","Name":"ฟาติน่า","Father":"-","Mom":"จ๋า","Sex":"F","Status":"1"},
{"uId":"137","Name":"อามิ","Father":"-","Mom":"จ๋า","Sex":"F","Status":"1"},
{"uId":"138","Name":"ชูใจ","Father":"เชล์","Mom":"-","Sex":"F","Status":"1"},
{"uId":"139","Name":"ชินโจ","Father":"เชล์","Mom":"-","Sex":"F","Status":"1"},
{"uId":"140","Name":"อลิส","Father":"เอ็ก","Mom":"-","Sex":"M","Status":"1"},
{"uId":"141","Name":"ชิ","Father":"เอี่ยว","Mom":"-","Sex":"M","Status":"1"},
{"uId":"142","Name":"ชาร์ค","Father":"เอี่ยว","Mom":"-","Sex":"M","Status":"1"},
{"uId":"143","Name":"ข่าวดี","Father":"ปอ","Mom":"-","Sex":"-","Status":"1"},
{"uId":"144","Name":"ปราดเปรียว","Father":"-","Mom":"โอ๊ด","Sex":"M","Status":"1"},
{"uId":"145","Name":"ปานปราชญ์","Father":"-","Mom":"โอ๊ด","Sex":"F","Status":"1"},
{"uId":"146","Name":"แป้งปั้น","Father":"-","Mom":"น้ำ","Sex":"F","Status":"1"},
{"uId":"147","Name":"ปันปัน","Father":"-","Mom":"น้ำ","Sex":"F","Status":"1"},
{"uId":"148","Name":"ดีเด่น","Father":"-","Mom":"ส้ม","Sex":"M","Status":"1"},
{"uId":"149","Name":"ชอปเปอร์","Father":"-","Mom":"ส้ม","Sex":"M","Status":"1"},
{"uId":"150","Name":"ดีดี","Father":"-","Mom":"ส้ม","Sex":"M","Status":"1"},
{"uId":"151","Name":"ไตเติล","Father":"-","Mom":"ควีน","Sex":"M","Status":"1"},
{"uId":"152","Name":"เดลต้า","Father":"เดียว","Mom":"-","Sex":"M","Status":"1"},
{"uId":"153","Name":"หัวแก้ว","Father":"-","Mom":"เก๋ง","Sex":"F","Status":"1"},
{"uId":"154","Name":"มังกร","Father":"-","Mom":"เก๋ง","Sex":"M","Status":"1"},
{"uId":"155","Name":"เตเต","Father":"เต๋","Mom":"-","Sex":"-","Status":"1"}
] 
p  = ""
Sex = ""
for i in vals:
    if i["Father"] == "-":
        p = i["Mom"]
    else:
        p = i["Father"]
    if i["Sex"] == "F":
        Sex = "Gender.FEMALE"
    else:
        Sex = "Gender.MALE"
        
    print(f'''family.addMember('{p}', '{i["Name"]}', {Sex}, 'CHILD')''')
#   family.addMember('บุญ', 'ช้วน', Gender.FEMALE, 'CHILD', 0)
    