import { FamilyTree } from '@/models/FamilyTree'
import { Member } from '@/models/Member'
import { Gender } from '@/types/Gender'

export const isMale = (member: Member): boolean => member.gender === Gender.MALE
export const isFemale = (member: Member): boolean =>
  member.gender === Gender.FEMALE

export const getName = (member: Member): string => member.name
export const getSpouse = (member: Member): Member | null => member.spouse

export const isMemberOrSpouse =
  (name: string) =>
  (member: Member): boolean =>
    member.name === name || member.spouse?.name === name

export const setupShanFamilyTree = (): FamilyTree => {
  //1st generation
  const family = new FamilyTree('บุญ', 'หงวน')

  //2nd Gen
  family.addMember('บุญ', 'ช้วน', Gender.FEMALE, 'CHILD', 0)
  family.addMember('บุญ', 'พิม', Gender.FEMALE, 'CHILD', 0)
  family.addMember('บุญ', 'พวน', Gender.FEMALE, 'CHILD', 0)
  family.addMember('บุญ', 'อาจ', Gender.MALE, 'CHILD', 0)
  family.addMember('บุญ', 'เอียด', Gender.FEMALE, 'CHILD', 0)
  family.addMember('บุญ', 'ออ', Gender.FEMALE, 'CHILD', 0)
  family.addMember('บุญ', 'ออง', Gender.FEMALE, 'CHILD', 0)
  family.addMember('บุญ', 'ควญ', Gender.FEMALE, 'CHILD', 0)
  family.addMember('บุญ', 'เครือ', Gender.FEMALE, 'CHILD', 0)
  family.addMember('บุญ', 'เยี่ยม', Gender.MALE, 'CHILD', 0)
  family.addMember('บุญ', 'ยั่ว', Gender.MALE, 'CHILD', 0)
  //3rd Gen

  family.addMember('ช้วน', 'วิเชียร', Gender.FEMALE, 'CHILD', 0)
  family.addMember('ช้วน', 'อุบล', Gender.FEMALE, 'CHILD', 1)
  family.addMember('พิม', 'นัน', Gender.FEMALE, 'CHILD', 0)
  family.addMember('พิม', 'นะ', Gender.MALE, 'CHILD', 0)
  family.addMember('พวน', 'สมศักดิ์', Gender.MALE, 'CHILD', 0)
  family.addMember('พวน', 'พะเยา', Gender.FEMALE, 'CHILD', 1)
  family.addMember('พวน', 'กันยา', Gender.FEMALE, 'CHILD', 1)
  family.addMember('พวน', 'ไพศาล', Gender.MALE, 'CHILD', 0)
  family.addMember('พวน', 'กอบแก้ว', Gender.FEMALE, 'CHILD', 1)
  family.addMember('พวน', 'อุไทยวรรณ', Gender.FEMALE, 'CHILD', 1)
  family.addMember('พวน', 'กาญจนา', Gender.FEMALE, 'CHILD', 1)
  family.addMember('อาจ', 'เทือง', Gender.FEMALE, 'CHILD', 0)
  family.addMember('เอียด', 'เอิญ', Gender.FEMALE, 'CHILD', 0)
  family.addMember('เอียด', 'กิ้น', Gender.FEMALE, 'CHILD', 0)
  family.addMember('เอียด', 'แจ๊ว', Gender.FEMALE, 'CHILD', 1)
  family.addMember('เอียด', 'ตู๋', Gender.MALE, 'CHILD', 1)
  family.addMember('ออ', 'คเน', Gender.MALE, 'CHILD', 1)
  family.addMember('ออ', 'ชำนาญ', Gender.MALE, 'CHILD', 0)
  family.addMember('ออ', 'คำนวน', Gender.FEMALE, 'CHILD', 1)
  family.addMember('ออง', 'ธนู', Gender.MALE, 'CHILD', 1)
  family.addMember('ออง', 'วินัย', Gender.MALE, 'CHILD', 0)
  family.addMember('ออง', 'ธานี', Gender.MALE, 'CHILD', 0)
  family.addMember('เครือ', 'เบ็ญจา', Gender.FEMALE, 'CHILD', 1)
  family.addMember('เครือ', 'คมคาย', Gender.FEMALE, 'CHILD', 1)
  family.addMember('เยี่ยม', 'โดม', Gender.MALE, 'CHILD', 0)
  family.addMember('เยี่ยม', 'แดง', Gender.FEMALE, 'CHILD', 1)
  family.addMember('เยี่ยม', 'แอ๊ด', Gender.MALE, 'CHILD', 0)
  family.addMember('เยี่ยม', 'ป๊อก', Gender.MALE, 'CHILD', 1)
  family.addMember('เยี่ยม', 'จุ๋มจิ๋ม', Gender.FEMALE, 'CHILD', 1)
  family.addMember('ยั่ว', 'นิตยา', Gender.FEMALE, 'CHILD', 1)
  family.addMember('ยั่ว', 'อารี', Gender.FEMALE, 'CHILD', 1)
  family.addMember('วิเชียร', 'ไก่', Gender.FEMALE, 'CHILD', 0)
  family.addMember('วิเชียร', 'กบ', Gender.FEMALE, 'CHILD', 1)
  family.addMember('วิเชียร', 'สุพัตรา', Gender.FEMALE, 'CHILD', 1)
  family.addMember('อุบล', 'ตู้น', Gender.MALE, 'CHILD', 1)
  family.addMember('อุบล', 'ต่อ', Gender.MALE, 'CHILD', 1)
  family.addMember('อุบล', 'ต่าย', Gender.MALE, 'CHILD', 1)
  family.addMember('นัน', 'เป็ด', Gender.FEMALE, 'CHILD', 1)
  family.addMember('นัน', 'เบื๊อกใหญ่', Gender.MALE, 'CHILD', 1)
  family.addMember('นัน', 'เบื๊อกเล็ก', Gender.MALE, 'CHILD', 1)
  family.addMember('นัน', 'แหม่ว', Gender.FEMALE, 'CHILD', 1)
  family.addMember('นะ', 'โต้ง', Gender.MALE, 'CHILD', 1)
  family.addMember('นะ', 'ตั้ว', Gender.MALE, 'CHILD', 1)
  family.addMember('นะ', 'ต้อย', Gender.MALE, 'CHILD', 1)
  family.addMember('นะ', 'หญิง', Gender.FEMALE, 'CHILD', 1)
  family.addMember('สมศักดิ์', 'ปุ๋ย', Gender.FEMALE, 'CHILD', 1)
  family.addMember('สมศักดิ์', 'อ้อ', Gender.FEMALE, 'CHILD', 1)
  family.addMember('พะเยา', 'ทิพ', Gender.FEMALE, 'CHILD', 1)
  family.addMember('พะเยา', 'เม้า', Gender.FEMALE, 'CHILD', 1)
  family.addMember('พะเยา', 'เพรช', Gender.FEMALE, 'CHILD', 1)
  family.addMember('พะเยา', 'ดำ', Gender.FEMALE, 'CHILD', 1)
  family.addMember('กันยา', 'หนึ่ง', Gender.MALE, 'CHILD', 1)
  family.addMember('กันยา', 'หนิง', Gender.FEMALE, 'CHILD', 1)
  family.addMember('ไพศาล', 'หญก', Gender.FEMALE, 'CHILD', 1)
  family.addMember('ไพศาล', 'กรีน', Gender.FEMALE, 'CHILD', 1)
  family.addMember('กอบแก้ว', 'เทป', Gender.MALE, 'CHILD', 1)
  family.addMember('กอบแก้ว', 'ทอป', Gender.MALE, 'CHILD', 1)
  family.addMember('อุไทยวรรณ', 'ทีม', Gender.MALE, 'CHILD', 1)
  family.addMember('อุไทยวรรณ', 'ยุ้ย', Gender.FEMALE, 'CHILD', 1)
  family.addMember('กาญจนา', 'น้ำ', Gender.FEMALE, 'CHILD', 1)
  family.addMember('กาญจนา', 'ภูมิ', Gender.MALE, 'CHILD', 1)
  family.addMember('เทือง', 'โหน่ง', Gender.FEMALE, 'CHILD', 1)
  family.addMember('เทือง', 'ศุกพชัย', Gender.MALE, 'CHILD', 1)
  family.addMember('เทือง', 'วรรณ', Gender.FEMALE, 'CHILD', 1)
  family.addMember('เทือง', 'มุกดา', Gender.FEMALE, 'CHILD', 1)
  family.addMember('เทือง', 'อุไร', Gender.FEMALE, 'CHILD', 1)
  family.addMember('เอิญ', 'กุ้ง', Gender.MALE, 'CHILD', 0)
  family.addMember('เอิญ', 'น้อย', Gender.FEMALE, 'CHILD', 1)
  family.addMember('เอิญ', 'สัน', Gender.MALE, 'CHILD', 1)
  family.addMember('เอิญ', 'แม๋ง', Gender.FEMALE, 'CHILD', 1)
  family.addMember('เอิญ', 'น้ำเพรช', Gender.FEMALE, 'CHILD', 1)
  family.addMember('เอิญ', 'ฮุก', Gender.MALE, 'CHILD', 1)
  family.addMember('แจ๊ว', 'จ๊ะ', Gender.FEMALE, 'CHILD', 1)
  family.addMember('แจ๊ว', 'มา', Gender.FEMALE, 'CHILD', 1)
  family.addMember('แจ๊ว', 'ต้า', Gender.FEMALE, 'CHILD', 1)
  family.addMember('ตู๋', 'จ๋า', Gender.FEMALE, 'CHILD', 1)
  family.addMember('ชำนาญ', 'วิ', Gender.FEMALE, 'CHILD', 1)
  family.addMember('ชำนาญ', 'เชล์', Gender.FEMALE, 'CHILD', 1)
  family.addMember('ชำนาญ', 'แก๊ป', Gender.FEMALE, 'CHILD', 1)
  family.addMember('คำนวน', 'อิฐ', Gender.MALE, 'CHILD', 1)
  family.addMember('คำนวน', 'เอ็ก', Gender.MALE, 'CHILD', 1)
  family.addMember('คำนวน', 'เอี่ยว', Gender.MALE, 'CHILD', 1)
  family.addMember('ธนู', 'ป่าน', Gender.FEMALE, 'CHILD', 1)
  family.addMember('ธนู', 'ปอ', Gender.MALE, 'CHILD', 1)
  family.addMember('ธานี', 'นุ่น', Gender.FEMALE, 'CHILD', 1)
  family.addMember('ธานี', 'น๊อต', Gender.MALE, 'CHILD', 1)
  family.addMember('เบ็ญจา', 'โอ๊ด', Gender.FEMALE, 'CHILD', 1)
  family.addMember('เบ็ญจา', 'น้ำ', Gender.FEMALE, 'CHILD', 1)
  family.addMember('คมคาย', 'เป็นปลื้ม', Gender.MALE, 'CHILD', 1)
  family.addMember('โดม', 'ส้ม', Gender.FEMALE, 'CHILD', 1)
  family.addMember('แดง', 'ควีน', Gender.FEMALE, 'CHILD', 1)
  family.addMember('แดง', 'เดียว', Gender.MALE, 'CHILD', 1)
  family.addMember('แดง', 'ดิว', Gender.MALE, 'CHILD', 1)
  family.addMember('แอ๊ด', 'ปอ', Gender.MALE, 'CHILD', 1)
  family.addMember('แอ๊ด', 'ตานอย', Gender.MALE, 'CHILD', 1)
  family.addMember('ป๊อก', 'ตุน', Gender.MALE, 'CHILD', 1)
  family.addMember('ป๊อก', 'ปอปอาย', Gender.MALE, 'CHILD', 1)
  family.addMember('ป๊อก', 'ติป', Gender.MALE, 'CHILD', 1)
  family.addMember('นิตยา', 'เก๋ง', Gender.FEMALE, 'CHILD', 1)
  family.addMember('นิตยา', 'จิป', Gender.MALE, 'CHILD', 1)
  family.addMember('อารี', 'โป้ง', Gender.MALE, 'CHILD', 1)
  family.addMember('อารี', 'โปรด', Gender.MALE, 'CHILD', 1)
  family.addMember('กบ', 'บอส', Gender.MALE, 'CHILD', 1)
  family.addMember('ต่อ', 'ใบบัว', Gender.MALE, 'CHILD', 1)
  family.addMember('เป็ด', 'ตาว', Gender.FEMALE, 'CHILD', 1)
  family.addMember('เป็ด', 'ติป', Gender.FEMALE, 'CHILD', 1)
  family.addMember('เป็ด', 'เต๋', Gender.MALE, 'CHILD', 1)
  family.addMember('เบื๊อกเล็ก', 'ใบบัว', Gender.FEMALE, 'CHILD', 1)
  family.addMember('เบื๊อกเล็ก', 'ใบหอม', Gender.FEMALE, 'CHILD', 1)
  family.addMember('แหม่ว', 'กัสจัง', Gender.MALE, 'CHILD', 1)
  family.addMember('แหม่ว', 'เกม', Gender.MALE, 'CHILD', 1)
  family.addMember('ตั้ว', 'ไตเติล', Gender.MALE, 'CHILD', 1)
  family.addMember('เม้า', ' แชมป์', Gender.MALE, 'CHILD', 1)
  family.addMember('เม้า', 'มิ้ง', Gender.MALE, 'CHILD', 1)
  family.addMember('หนึ่ง', 'นิว', Gender.MALE, 'CHILD', 1)
  family.addMember('หนิง', 'นน', Gender.MALE, 'CHILD', 1)
  family.addMember('หญก', 'ราแม', Gender.FEMALE, 'CHILD', 1)
  family.addMember('กรีน', 'ต้นกล้า', Gender.MALE, 'CHILD', 1)
  family.addMember('กรีน', 'กัปตัน', Gender.MALE, 'CHILD', 1)
  family.addMember('น้อย', 'ปืน', Gender.MALE, 'CHILD', 1)
  family.addMember('น้อย', 'ปลาย', Gender.MALE, 'CHILD', 1)
  family.addMember('มา', 'ของขวัญ', Gender.FEMALE, 'CHILD', 1)
  family.addMember('จ๋า', 'ฟาติน่า', Gender.FEMALE, 'CHILD', 1)
  family.addMember('จ๋า', 'อามิ', Gender.FEMALE, 'CHILD', 1)
  family.addMember('เชล์', 'ชูใจ', Gender.FEMALE, 'CHILD', 1)
  family.addMember('เชล์', 'ชินโจ', Gender.FEMALE, 'CHILD', 1)
  family.addMember('เอ็ก', 'อลิส', Gender.MALE, 'CHILD', 1)
  family.addMember('เอี่ยว', 'ชิ', Gender.MALE, 'CHILD', 1)
  family.addMember('เอี่ยว', 'ชาร์ค', Gender.MALE, 'CHILD', 1)
  family.addMember('ปอ', 'ข่าวดี', Gender.MALE, 'CHILD', 1)
  family.addMember('โอ๊ด', 'ปราดเปรียว', Gender.MALE, 'CHILD', 1)
  family.addMember('โอ๊ด', 'ปานปราชญ์', Gender.FEMALE, 'CHILD', 1)
  family.addMember('น้ำ', 'แป้งปั้น', Gender.FEMALE, 'CHILD', 1)
  family.addMember('น้ำ', 'ปันปัน', Gender.FEMALE, 'CHILD', 1)
  family.addMember('ส้ม', 'ดีเด่น', Gender.MALE, 'CHILD', 1)
  family.addMember('ส้ม', 'ชอปเปอร์', Gender.MALE, 'CHILD', 1)
  family.addMember('ส้ม', 'ดีดี', Gender.MALE, 'CHILD', 1)
  family.addMember('ควีน', 'ไตเติล', Gender.MALE, 'CHILD', 1)
  family.addMember('เดียว', 'เดลต้า', Gender.MALE, 'CHILD', 1)
  family.addMember('เก๋ง', 'หัวแก้ว', Gender.FEMALE, 'CHILD', 1)
  family.addMember('เก๋ง', 'มังกร', Gender.MALE, 'CHILD', 1)
  family.addMember('เต๋', 'เตเต', Gender.MALE, 'CHILD', 1)

  return family
}
